### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by LJSTARbird** [Xeeynamo/RSDK#2]
I'm posting this here again for convinience for you :P

- Apparently, the electrecity.bin crashes the program (when you scroll to see the last frames)
- The Play / Stop seems a bit weird on my end, it plays animations automatically (and loop at times) and I cannot stop / play it manually.
(Sometimes, some animations doesn't play at all as well, i'm not sure about it if it's from my end or not)
- Next to the "+" / "-" icons (to add or remove frames), maybe adding something to see the total numbers of frame of the animation ?
- A "duplicate animation" feature and maybe a "duplicate frame" as well would be neat

**Comment by Xeeynamo** [comment]
I am investigating on play/stop button and electicity.bin bug. Duplicate animation is coming soon :)

**Comment by Xeeynamo** [comment]
Frame duplication is completed.
