### ISSUE TITLE
Is this ever gonna get updated?

### ISSUE THREAD

**Issue by DoctorMario606** [Xeeynamo/RSDK#3]
I was just wondering because some features are really unstable. Like, the zoom in button, it doesnt work unless you click out and back in to the animation you were editing and it gets annoying fast. And there should also be a another way to move the camera (or whatever you call it) of the sheet around without typing in numbers all the time. There are MANY more suggestions and complaints I have but im pretty sure half of them will be fixed in the next update, whenever that comes...

**Comment by Xeeynamo** [comment]
Hello, I have updated it right now!
