### ISSUE TITLE
There's an issue to this thing,

### ISSUE THREAD

**Issue by Atekuro95** [Xeeynamo/RSDK#4]
I'm working on the sonic 1 sprite mod for sonic mania, but when I imported the sonic sprite gifs, it does nothing, just look. 
![image](https://user-images.githubusercontent.com/22590518/31576999-7552d328-b0bb-11e7-8706-4fb3294f46f1.png)

**Comment by Xeeynamo** [comment]
Have you tried to load Data\Animation\Sonic.ani instead of Data\Sprite\Player\Sonic1.gif?

**Comment by Atekuro95** [comment]
nope, I don't have the animation folder in the mania data folder.

**Comment by Atekuro95** [comment]
okay never mind, I solved it.

**Comment by Atekuro95** [comment]
but too bad I can't duplicate the frames.
