### ISSUE TITLE
Sonic CD spritesheets bigger than 256x256

### ISSUE THREAD

**Issue by aaronlink127** [Xeeynamo/RSDK#6]
When trying to refer past 256, it truncates the value to be below or exactly 64 when saving. Like when trying to set top to 299, it saves it as 43 because 299%256 is 43

**Comment by Xeeynamo** [comment]
I am sorry, but Sonic CD does not supports sprites bigger than 256x256 pixels. It is a limitation of RSDKv3 (Sonic CD / 1 / 2), not of the animation editor.
