### ISSUE TITLE
Sonic CD animation editing

### ISSUE THREAD

**Issue by ishmael205** [Xeeynamo/RSDK#8]
I know the focus of this tool is for Mania, but I've also used this tool for Sonic CD. There's a huge problem when using it for Sonic CD, however, and that's whenever you change the sprite location. It doesn't save the new sprite location to the .Ani file. It'll save every other change you make for CD except for that. Would you mind looking into that?

**Comment by Xeeynamo** [comment]
Thank you for this report. Since the Animation Editor is meant to work from Sonic CD to Mania, it is a priority to fix it. I will keep you updated about fixing progress here.

**Comment by ishmael205** [comment]
Sweet, sounds cool.

**Comment by Xeeynamo** [comment]
Fixed!
https://github.com/Xeeynamo/RSDK/releases/tag/1.2.1

**Comment by ishmael205** [comment]
You've done God's work.

**Comment by ishmael205** [comment]
Not sure if it's me doing something wrong, but the "left" and "top" values of the sprite property seem to not save, but the everything else does.
This is what it looked like before I save: https://i.imgur.com/zTovsh4.png
This is what happens when I save and reopen the Sonic CD .ani file: https://i.imgur.com/LwAeU8v.png
