### ISSUE TITLE
Texture editor won't remove sheet

### ISSUE THREAD

**Issue by TorutheRedFox** [Xeeynamo/RSDK#9]
I went ahead to add an extra spritesheet to the animation file and I misclicked and added sonic3.gif again, and now I can't delete it because the removal doesn't save

**Comment by Xeeynamo** [comment]
I fixed it on 1.2.2 (published right now), I am sorry for the issue.

**Comment by TorutheRedFox** [comment]
ok

**Comment by TorutheRedFox** [comment]
it still doesn't work though
